export default {
  ///
  emailIsRequired: 'البريد الالكتروني مطلوب',
  invalidEmail: 'بريد إلكتروني خاطئ',
  passwordIsRequired: 'كلمة المرور مطلوبة',
  invalidPassword: 'رمز مرور خاطئ',
  confirmPasswordIsRequired: 'تأكيد كلمة المرور مطلوب',
  invalidConfirmPassword: 'تأكيد كلمة المرور غير صالحة',
  passwordsDontMatch: 'كلمات المرور غير متطابقة',
  contactIsRequired: 'الاتصال مطلوب',
  invalidcontact: 'اتصال غير صالح',
  nameIsRequired: 'مطلوب اسم',

  ///

  registerSuccessfully: 'مسجل بنجاح',
  /////
  splashscreen: 'Splash',
  skip: 'يتخطى',
  professional: 'المتخصص المحترف قريب',
  profdesc:
    'الآن أصبح من السهل جدًا العثور على الخدمة المنزلية الخاصة بك، فلدينا الكثير من المتخصصين ذوي الخبرة العالية',
  onboardingscreen: 'OnBoarding',
  welcomescreen: 'Welcome',
  onlywomen: 'هذا التطبيق مسموح للنساء فقط',
  register: 'سجل باسم',
  bussiness: 'عمل',
  user: 'مستخدم',
  alreadyhaveacc: 'هل لديك حساب؟',
  sign_In: 'تسجيل الدخول',
  buttonopacity: 0.7,
  service_detial: 'تفاصيل الخدمات',
  loginscreen: 'Login',
  signupscreen: 'Signup',
  signupUser: 'SignupUser',
  signupArtist: 'SignupArtist',
  total_Duration: 'المدة الإجمالية',
  total_Cost: 'التكلفة الإجمالية',
  signin: 'تسجيل الدخول',
  travel_Cost: 'تكلفة النقل',
  welcomeback: 'أهلاً! مرحبًا بعودتك، لقد افتقدتك',
  email: 'بريد إلكتروني',
  password: 'كلمة المرور',
  forgotpassword: 'هل نسيت كلمة السر؟',
  orsignin: 'أو قم بتسجيل الدخول باستخدام',
  orsignup: 'أو قم بالتسجيل مع',
  donthaveacc: 'ليس لديك حساب؟ اشتراك',
  createacc: 'إنشاء حساب',
  fillinfo: 'املأ معلوماتك أدناه أو قم بالتسجيل باستخدام \n حسابك الاجتماعي.',
  name: 'اسم',
  jhon: 'فلان الفلاني',
  phonenum: 'رقم التليفون',
  num: '603.555.0123',
  expemail: 'example@gmail.com',
  pass: '********',
  address: 'عنوان',
  businessemail: 'بريد العمل',
  businessname: 'الاسم التجاري',
  Businessbrand: 'العلامة التجارية التجارية',
  services: 'خدمات',
  businesspayment: 'حساب الدفع التجاري',
  ibannum: 'رقم الحساب الدولي (IBAN).',
  agreewithterms: 'أتفق مع الشروط والأحكام',
  signup: 'اشتراك',
  category: 'الفئة',
  selectCategory: 'اختر الفئة',
  locationscreen: 'Location',
  whatloction: 'ما هو موقعك؟',
  needlocation: 'نحن بحاجة إلى معرفة موقعك من أجل اقتراح الخدمات القريبة.',
  selectcity: 'اختر مدينة',
  allcities: 'جميع المدن',
  allowloc: 'السماح بالوصول إلى الموقع',
  addLocation: 'إضافة الموقع',
  enterlocman: 'أدخل الموقع يدويا',
  getartist: 'احصل على أفضل فنان\n على عتبة داركم',
  manuallocationscreen: 'ManualLocation',
  enteryourlocation: 'أدخل موقعك',
  goldenavnue: 'الجادة الذهبية',
  usecurrenloc: 'استخدم موقعي الحالي',
  searchresult: 'نتيجة البحث',
  prestonroad: '8502 طريق بريستون. إنجليزي..',
  uploaddocsscreen: 'UploadDocuments',
  uploaddocs: 'تحميل المستندات والصور',
  uploadworklicense: 'قم بتحميل رخصة عملك',
  uploadyourdocs: 'قم بتحميل المستند الخاص بك هنا',
  uploadIdcard: 'قم بتحميل الرقم القومي الخاص بك',
  uploadwork: 'قم بتحميل صور عملك',
  dumytext: 'لوريم إيبسوم دولور الجلوس أميت كونسيكتور.',
  uploadphotos: 'تحميل الصور',
  compsignup: 'أكمل التسجيل',
  homescreen: 'Home',
  bottomTab: 'Bottom Tab',
  managePaymentScreen: 'ManagePayment',
  location: 'موقع',
  newyork: 'نيويورك، الولايات المتحدة الأمريكية',
  profileapprove: 'تمت الموافقة على ملفك الشخصي',
  setavailability: 'تعيين التوفر',
  online: 'متصل',
  activebooking: 'الحجوزات النشطة',
  totalbooking: 'مجموع حجوزات',
  totalview: 'إجمالي العرض',
  totalfavorite: 'مجموع المفضلة',
  myearning: 'أجوري',
  thismonth: 'هذا الشهر',
  sr: 'ريال سعودي',
  myservices: 'خدماتي',
  seeall: 'اظهار الكل',
  seeLess: 'انظر أقل',
  earning: 'الأرباح',
  wallet: 'محفظة',
  $: 'دولارًا',
  managePayout: 'إدارة الدفعات',
  paymentHistory: 'تاريخ الدفع',
  pendigEarnings: 'الأرباح المعلقة',
  widthraw: 'عمليات السحب',
  transactionTitle: 'اسم عنوان المعاملة',
  price: '0.00 ر.س',
  description: 'وصف',
  saudiaPrice: ' 0.00 ريال سعودي',
  myServices: 'خدماتي',
  noServicesAddedd: 'لم تتم إضافة أي خدمات',
  loriumText:
    'لوريم إيبسوم دولور الجلوس أميت كونسيكتور. اجلس في turpis not ante في وقت غير مناسب.',
  addService: 'أضف الخدمات',
  haircut: 'قصات شعر',
  makeup: 'ماكياج',
  shaving: 'حلق',
  hairdry: 'جفاف الشعر',
  massage: 'تدليك',
  henna: 'الحناء',
  nailcare: 'العناية بالأظافر',
  feetcare: 'العناية بالقدمين',
  skincare: 'العناية بالبشرة',
  next: 'التالي',
  artist: 'فنان',
  jenny: 'جيني ويلسون',
  profile: 'حساب تعريفي',
  yourprofile: 'ملفك الشخصي',
  offdays: 'أيام العطلة',
  membership: 'عضوية',
  paymentmethod: 'طرق الدفع',
  travelcost: 'تكاليف السفر',

  settings: 'إعدادات',
  transaction: 'المعاملات',
  helpcenter: 'مركز المساعدة',
  privacypolicy: 'سياسة الخصوصية',
  logout: 'تسجيل خروج',
  profilescreen: 'Profile',
  travelCostscreen: 'TravelCost',
  artistdetailscreen: 'ArtistDetails',
  artistDetailsUser: 'ArtistDetailsUser',
  addServices: 'AddServices',
  Services: 'Services',
  MyService: 'MyService',
  add_Service_Photos: 'إضافة صور الخدمة',
  lorem_ipsum: 'لوريم إيبسوم دولور الجلوس أميت كونسيكتور.',
  service_Description: 'وصف الخدمة',
  add_Service_Description: 'أضف وصف الخدمة',
  add_Title_and_Rates: 'أضف العنوان والأسعار',
  title: 'عنوان',
  faux_hawk: 'صقر زائف',
  rates: 'معدلات',
  SR_24: '24.00 ريال سعودي',
  add_More_Types: 'إضافة المزيد من الأنواع + ',
  payment_Mode: 'طريقة الدفع',
  credit_Card: 'بطاقة إئتمان',
  Cash: 'نقدي',
  duration_Time: 'وقت المدة',
  hair_Cut: 'حلاقة شعر',
  hair_Coloring: 'صبغ شعر',
  hair_Wash: 'غسل الشعر',
  type20: '20 نوعا',
  type12: '12 نوعا',
  edit: 'يحرر',
  jobdone: 'إنجاز المهمة: 20',
  jobcancel: 'إلغاء الوظيفة: 01',
  zero_One: '01',
  min15: '15 دقيقة',
  km15: '1.5 كم',
  pm11: '11 مساءً',
  am11: '11 صباحًا',
  monsun: 'مون صن',
  travelingcost: 'تكلفة السفر 20 ريال سعودي',
  travelingCost: 'تكلفة السفر',
  favorite: '    المفضلة (50)',
  review: '4.8 (1k+ مراجعة)',
  gallery: 'صالة عرض',
  review1: 'مراجعة',
  aboutus: 'معلومات عنا',
  selectHairCut: 'حدد قص الشعر',
  dollar24: '24.00 دولارًا',
  dollar: 'دولارًا',
  mohawk: 'الموهوك',
  buzz_cut: 'قطع الطنانة',
  pompadour: 'بومبادور',
  side_part: 'جزء جانبي',
  crew_cut: 'قطع الطاقم',
  add_Type: 'أضف النوع',
  booking: 'الحجوزات',
  booking_Detail: 'تفاصيل الحجز',
  remind_Me: 'ذكرني',
  aug_25: '25 أغسطس 2024 - 10:00 صباحًا',
  g85: 'G8502 طريق بريستون. إنجليوود',
  service_id: '   معرف الخدمة: #HR452SA54',
  view_Detail: 'عرض التفاصيل',
  cancle: 'يلغي',
  comming_Tab: 'قادم',
  cancled: 'ألغيت',
  view_Electric_Recipt: 'عرض الإيصال الإلكتروني',
  rebook: 'إعادة الحجز',
  aug_28: '28 أغسطس 2024 - الساعة 10:00 صباحًا',
  upcoming: 'القادمة',
  completed: 'مكتمل',
  onGoing: 'ألغيت',
  you_have: 'لقد وصلت إلى موقع الحلاقة/الصالون',
  ok: 'نعم',
  arrived: 'ArrivedLocation',
  new_Booking_Request: 'New Booking Request',
  july_Time: '25 أغسطس 2024 - 10:00 صباحًا',
  type08: '08 أنواع',
  type04: '04 أنواع',
  type05: '05 أنواع',
  types: 'أنواع',
  alservice: 'الخدمات (18)',
  allservice: 'الخدمات',
  addservices: ' + إضافة الخدمات',
  face_makeup: 'مكياج الوجه',
  zerotime: '00:00 - 00:00',
  getDirection: 'احصل على اتجاه',
  cancel_Request: 'Cancle Request',
  bookingAccepted: 'الحجز مقبول',
  contactUs: 'اتصل بنا',
  callNumber: '(406) 555-0120',
  exampleEmail: 'example@gmail.com',
  viewOnMap: 'عرض على الخريطة',
  prestonRd: '8502 طريق بريستون. إنجليوود، مين 98380',
  bookingDetail: 'الحجز مقبول',
  threeKm: '3.5 كم/50 دقيقة',
  serviceRequired: 'الخدمات المطلوبة',
  dollar_24: '24.00 ريال',
  saudiRiyal: 'ريال',
  decline: 'انخفاض',
  request_reservation: 'طلب حجز جديد',
  rs: 'رس',
  booking_Completed: 'اكتمل الحجز',
  you_Have_Been: 'لقد اكتملت بنجاح!',
  How_was: 'كيف كانت تجربتك مع جيني؟',
  your_Overall: 'تقييمك العام',
  add_Detail_Review: 'إضافة مراجعة مفصلة',
  enter_Here: 'أدخل هنا',
  addPhoto: 'إضافة صورة',
  submit: 'يُقدِّم',
  cancellation_Boking: 'إلغاء الحجز',
  please_specify: 'الرجاء تحديد سبب الإلغاء:',
  change_the: 'تغيير الجدول الزمني',
  weather_conditions: 'احوال الطقس',
  availability_of_parking: 'توافر مواقف السيارات',
  lack_amenities: 'عدم وجود وسائل الراحة',
  alternative_Option: 'لدي خيار بديل',
  last: 'آخر',
  enter_Your_Reason: 'أدخل السبب الخاص بك',
  workinghours: 'إضافة ساعات العمل',
  addhours: 'أضف ساعات',
  photos: 'الصور (8)',
  photosLength: 'الصور',
  addphotos: 'إضافة صورة',
  weather_Conditions: 'احوال الطقس',
  availability_Parking: 'توافر مواقف السيارات',
  lack_Of_Amenities: 'عدم وجود وسائل الراحة',
  i_have_Alternative_Option: 'لدي خيار بديل',
  basic_Membership_Plan: 'خطة العضوية الأساسية',
  free: 'حر',
  includes: 'يشمل',
  offline_booking: 'الحجز دون اتصال',
  chat_with_custumer: 'الدردشة مع العملاء قبل الحجز',
  future_booking: 'الحجز المستقبلي وتواريخ التوقف التي يحددها الفنان',
  active: 'نشيط',
  travel_Cost_PerKilo: 'تكلفة السفر لكل كيلومتر',
  sr4: 'SR4.00',
  save: 'يحفظ',
  mon: 'الاثنين',
  octfive: '5 Oct',
  addMoreOff: 'إضافة المزيد من إيقاف',
  pay_Cash: 'الدفع نقدا',
  credit_Debit: 'بطاقة الائتمان والخصم',
  add_New_Card: 'إضافة بطاقة جديدة',
  notification_setting: 'إعدادات الإشعار',
  password_manager: 'مدير كلمة السر',
  delete_account: 'حذف الحساب',
  your_Transaction: 'المعاملات الخاصة بك',
  today: 'اليوم',
  april_date: '24 أبريل | 7:30 صباحا',
  twenty_Dollar: '- 20.00 دولارًا',
  yesterday: 'أمس',
  thirty_Dollar: '- 30.00 دولارًا',
  twenty_july: '22 يوليو 2023',
  hair_Color: 'لون الشعر',
  twenty_One_July: '21 يوليو 2023',
  current_Password: 'كلمة السر الحالية',
  new_Password: 'كلمة المرور الجديدة',
  confirm_Password: 'تأكيد كلمة المرور الجديدة',
  change_Password: 'تغيير كلمة المرور',
  seek: 'يبحث',
  instructions: 'التعليمات',
  callUs: 'اتصل بنا',
  everyone: 'الجميع',
  general: 'عام',
  account: 'حساب',
  signature_Saloon: 'ما هو صالون التوقيع؟',
  lorium_ispum_text:
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut Labore et dolore magna aliqua.',
  how_To_Cancle: 'كيفية إلغاء حجز الموعد؟',
  how_To_See_Preseverd: 'كيف ترى الصالون المحفوظ؟',
  check_Previosly_Booking: 'كيفية التحقق من الموعد المحجوز مسبقًا؟',
  verify_Transaction: 'كيفية التحقق من المعاملة؟',
  check_nearby_Saloon: 'كيفية إضافة شيك للصالون القريب؟',
  add_Review: 'كيفية إضافة مراجعة؟',
  customer_Service: 'خدمة الزبائن',
  whatsapp: 'واتساب',
  website: 'موقع إلكتروني',
  facebook: 'فيسبوك',
  twitter: 'تويتر',
  instagram: 'انستغرام',
  four_Number: '555-0103 (480)',
  addresses: 'عناوين',
  address_Dummy: '84 طريق دبليو لا إنترادا، كوراليس، نيويورك، الولايات المتحدة',
  newYork_address: 'نيويورك، الولايات المتحدة',
  uploadworkphotos: 'قم بتحميل صور عملك',
  uploadphotoshere: 'تحميل الصور الخاصة بك هنا',
  photocategory: 'فئة الصور',
  hairname: 'اسم الشعر',
  addtype: 'أضف النوع',
  reviews: 'التعليقات',
  searchreviews: 'البحث في المراجعات',
  filter: 'منقي',
  verified: 'تم التحقق',
  latest: 'أحدث',
  withphotos: 'مع الصور',
  detailedreview: 'مراجعات مفصلة',
  opennow: 'مفتوح الان',
  dalethiel: 'ديل ثيل',
  followers45: '45 متابع',
  monthsago11: 'قبل 11 أشهر',
  tiffny: 'تيفاني نيتشه',
  dateOfBirth: 'تاريخ الميلاد',
  dayMonthYear: 'يوم/شهر/سنة',
  gender: 'جنس',
  heChooses: 'يختار',
  updateProfile: 'تحديث الملف',
  are_You_Sure: 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
  yes_Logout: 'نعم، تسجيل الخروج',
  privacy_Policy: 'سياسة الخصوصية',
  canclation_Policy: 'سياسة الإلغاء',
  terms_and_Condition: 'الشروط والأحكام',
  dummy_Text_Policy:
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut Labore et dolore magna aliqua. إننا لا نسمح إلا بالحد الأدنى من النشاط الذي نمارسه من خلال العمل، ولا نتركه بعيدًا عن أي شيء يترتب على ذلك.',
  dummy_Text_Lorium:
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut Labore et.',
  lorium_Text_Small:
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt',
  edit_About: 'تحرير حول',
  modify_Working_Hour: 'تعديل ساعات العمل',
  social_Media: 'وسائل التواصل الاجتماعي',
  social_Media_Editing: 'تحرير وسائل الاعلام الاجتماعية',
  artistUser: '@artistuser',
  editing_Contact_Detail: 'تحرير تفاصيل الاتصال',
  hairCut_HairStyling: 'قص الشعر ومصفف الشعر',
  special_Offer: 'باقة العروض الخاصة، صالحة حتى 10 ديسمبر 2024',
  onetwofiveDollar: '125.00 دولارًا',
  bookNow: 'احجز الآن',
  continuemobile: 'تواصل مع الجوال',
  SignupUser: 'SignupUser',
  userHome: 'UserHome',
  servicesDesc: 'احصل على أفضل\n فنان\n على عتبة داركم',
  searchsaloon: 'صالون البحث، متخصص...',
  toprated: 'الفنانين الأعلى تقييمًا',
  nearartist: 'بالقرب من الفنان',
  onlinestore: 'محلات نشطة',
  onlinestorescreen: 'OnlineStores',
  onlinestoresdetailcreen: 'OnlineStoreDetail',
  brand_Name: 'اسم العلامة التجارية',
  visiting_Site: 'زيارة الموقع',
  notice: 'إشعار',
  userArtist: 'UserArtistScreem',
  addworkinghour: 'إضافة ساعات العمل',
  adddesc: 'اضف وصفا',
  enterdesc: 'أدخل الوصف',
  contactndadress: 'أضف العنوان والاتصال',
  change: 'يتغير',
  premiummember: "'خطة العضوية المميزة'",
  riyal50: '50.00 ريال سعودي',
  subcribenow: 'اشترك الآن',
  off: 'عن',
  notification_screen: 'Notifications',
  notification: 'إشعارات',
  user_Bottom_Stack: 'UserBottomStack',
  travelCost_20: 'تكلفة السفر 20 ريال',
  moonSoon: 'مون صن | 11 صباحًا - 11 مساءً',
  comments: '(107 تعليق)',
  cancelation: 'الإلغاءات',
  jobDone: 'تم إنجاز المهمة',
  startingFrom: 'يبدأ من 24.00 رس',
  timeduration: 'المدة الإجمالية 1 ساعة',
  bookapointment: 'حجز',
  riyal28: '28.00 رس',
  cancelbooking:
    'قد يقوم الفنان بإلغاء حجزك بسبب \n ساعة الخدمات على وشك الانتهاء',
  oneselect: 'تم اختيار خدمة واحدة',
  workinghour: 'ساعات العمل',
  bookapointment_screen: 'BookAppointment',
  bookAppointment_screen: 'BookAppointment',
  bookingDetails_screen: 'BookingDetails',
  bookapoint: 'موعد الكتاب',
  forcancelation:
    'للإلغاء، يجب أن يفرض أي حجز على العميل وديعة تتراوح بين 20-50% من التكلفة الإجمالية',
  hour: '1 ساعة',
  youraddress: 'عنوانك',
  changeaddress: 'تغيير العنوان',
  day: 'يوم',
  time: 'وقت',
  saved: 'أنقذ',
  useryourprofile_screen: 'UserYourProfile',
  saved_screen: 'Saved',
  onehour: 'المدة 1 ساعة',
  userNotificationsScreen: 'UserNotifications',
  congrate_Your_Reservation: 'تهانينا، لقد تم تأكيد حجزك لجلسة سبا مريحة.',
  your_Favorite_hairStyle:
    'مصففة الشعر المفضلة لديك، ليزا، متاحة للمواعيد يوم الأربعاء.',
  estimated_Weight_Time: 'وقت الانتظار المقدر في الصالون هو حوالي 25 دقيقة.',
  augs17: '17 أغسطس 2023',
  augs18: '18 أغسطس 2023',
  fifty_Percent_Discount: 'خصم 50% على صبغات الشعر!',
};
